name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install deps
        run: |
          chmod +x test_engine/ios_deps.sh
          ./test_engine/ios_deps.sh
      - name: Build
        run: |
          cargo lipo --release
          cd mobile/iOS
          xcodebuild -showsdks
          xcodebuild -sdk iphonesimulator -scheme TestEngine build