name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Debug
        run: |
          cd mobile/iOS
          xcodebuild -showsdks
          xcodebuild -list
          pwd
      - name: Build
        run: python3 build.py ios