name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        run: |
          chmod +x linux_deps.sh 
          sudo ./linux_deps.sh 
      - name: Build
        run:  cargo build