name: Mac

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macOS
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Mac
        run: arch -arm64 cargo build