name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: Windows
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: windows
        run: cargo build